version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapi_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"

    volumes:
      - ./api:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: ahmed12e

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - ./api:/myapp
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: ahmed12e

volumes:
  pgdata:
